# Generated by Django 5.0.6 on 2024-07-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('dtCriacao', models.DateTimeField(auto_now_add=True)),
                ('dtFinalizado', models.DateTimeField(null=True)),
            ],
        ),
    ]
