# Generated by Django 5.0.6 on 2024-07-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='dtFinalizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
